apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "test1"

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 3
          echo "hello world"
  build-1:
      steps:
        - name: Say hello
          uses: docker://golang:1.20.3-alpine3.17
          shell: sh
          run: |
            sleep 5
            exit 1
