name: tag

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "*"
jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: register-artifact-step-with-options
        uses: cloudbees-io-gha/register-build-artifact@v3
        with:
          name: Docker-artifact
          url: https://hub.docker.com/repository/docker/hackers
          version: 1.0.0
          label: "Comp"
          component-id : "b46aedc4-cc00-42f8-910f-f79e2c09e4cd"

      - name: register-artifact-step-with-options - no comp
        uses: cloudbees-io-gha/register-build-artifact@v3
        with:
          name: KN-Docker-artifact
          url: https://hub.docker.com/repository/docker/hackers
          version: 1.0.0
          label: "No comp"
          

  run-scheduled-task-1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run some scheduled task
        run: |
          echo "This is a scheduled run every 5 minutes."
          # Your actual commands can go here, like tests, builds, etc.
